# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 349396f3bb4aec55247df8ac9c330249024a17787734e67b825deebcc2148273a5163001f548e4b10e38a11f8daef92a45dbcbef7f2c025fe492ebc7d2a4aa99

test:
  secret_key_base: c06dae11affaeb3007f34a28360514712877cf5f5090469f76a1451396791a03c0e3d31e915c8c32fc8e260848575205b8b56762563d2e3cfde8f7c954806107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
